---
apiVersion: v1
kind: Namespace
metadata:
  name: vm-test

---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  namespace: vm-test
  name: single-gpu
spec:
  spec:
    devices:
      requests:
      - name: gpu
        exactly:
          deviceClassName: gpu.example.com

---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  namespace: vm-test
  name: testvm
spec:
  runStrategy: Halted
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      resourceClaims:
      - name: gpu-claim
        resourceClaimTemplateName: single-gpu
      readinessProbe:
        tcpSocket:
          port: 22
        initialDelaySeconds: 0
        periodSeconds: 5
        timeoutSeconds: 5
        successThreshold: 3
        failureThreshold: 1
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          gpus:
          - claimName: gpu-claim
            name: example-gpu
            requestName: gpu
        resources:
          requests:
            memory: 256M
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:43
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              system_info:
                default_user:
                  name: test
              password: test
              chpasswd:
                expire: false
              ssh_pwauth: yes
              ssh_authorized_keys:
                - ssh-rsa the public key
